#!/usr/bin/env python3
"""Phase 4 campaign stats: per-frame metrics (cached npz) -> paired stats -> markdown.

Protocol windows (documented deviations from naive means):
- LC:  f93 single-frame (headline gate) + mean over generated region [93:].
       first_div is codec-noise-polluted (~60dB from frame 0) -> fixed windows.
- HY:  mean over frames [13:] (post context-chunk; chunk0 = 13 px frames).
- SF:  VBench MUSIQ prefix windows (350/700 for 180-latent; 1400 for 360-latent).
- QVG reps are same-seed repeats (atomic_add nondeterminism), pca/bf16 n=1.
"""
import os, sys, glob, json, subprocess, re
import numpy as np

os.chdir("/home/zhizhousha/workspace/video-project/Quant-VideoGen")
NPZD = "repro/0718/npz"; os.makedirs(NPZD, exist_ok=True)
PY = ".venv/bin/python"
DEV = "cuda"

_lp = None
def lp():
    global _lp
    if _lp is None:
        import lpips, torch
        _lp = lpips.LPIPS(net="vgg").to(DEV)
    return _lp

def calc_ssim(a, b):
    import torch.nn.functional as F
    C1, C2 = 0.01**2, 0.03**2
    a, b = a.unsqueeze(0), b.unsqueeze(0)
    mu1, mu2 = F.avg_pool2d(a, 11, 1, 5), F.avg_pool2d(b, 11, 1, 5)
    s1 = F.avg_pool2d(a*a, 11, 1, 5) - mu1**2
    s2 = F.avg_pool2d(b*b, 11, 1, 5) - mu2**2
    s12 = F.avg_pool2d(a*b, 11, 1, 5) - mu1*mu2
    return float((((2*mu1*mu2+C1)*(2*s12+C2)) / ((mu1**2+mu2**2+C1)*(s1+s2+C2))).mean())

def ref_metrics(ref_path, test_path, key):
    """Per-frame PSNR/SSIM/LPIPS(paper conv) of test vs ref, cached."""
    f = f"{NPZD}/{key}.npz"
    if os.path.exists(f):
        d = np.load(f); return d["psnr"], d["ssim"], d["lpips"]
    import imageio.v3 as iio, torch
    ref = list(iio.imiter(ref_path, plugin="pyav"))
    P, S, L = [], [], []
    for i, tf in enumerate(iio.imiter(test_path, plugin="pyav")):
        if i >= len(ref): break
        a = torch.from_numpy(np.asarray(ref[i])).float().permute(2,0,1)/255
        b = torch.from_numpy(np.asarray(tf)).float().permute(2,0,1)/255
        mse = float(((a-b)**2).mean())
        P.append(10*np.log10(1/mse) if mse > 0 else 99.0)
        S.append(calc_ssim(a, b))
        import torch as _t
        with _t.no_grad():
            L.append(float(lp()(a.unsqueeze(0).to(DEV), b.unsqueeze(0).to(DEV))))
    P, S, L = map(np.array, (P, S, L))
    np.savez(f, psnr=P, ssim=S, lpips=L)
    return P, S, L

_vb_cache_file = f"{NPZD}/vbench.json"
_vb = json.load(open(_vb_cache_file)) if os.path.exists(_vb_cache_file) else {}
def vbench(path):
    if path in _vb: return _vb[path]
    r = subprocess.run([PY, "repro/backup/scripts/vbench_iq.py", path], capture_output=True, text=True)
    line = [l for l in r.stdout.splitlines() if l.startswith(path)]
    if not line: raise RuntimeError(f"vbench failed for {path}: {r.stderr[-300:]}")
    d = {}
    for m in re.finditer(r'(\d+)f=([\d.]+|--)', line[0]):
        if m.group(2) != '--': d[m.group(1)] = float(m.group(2))
    d['full'] = float(re.search(r'full=([\d.]+)', line[0]).group(1))
    _vb[path] = d
    json.dump(_vb, open(_vb_cache_file, "w"), indent=0)
    return d

def sign_test(diffs, direction=1):
    """One-sided sign test p-value that median(diffs*direction) > 0."""
    from math import comb
    d = [x for x in diffs if x != 0]
    n = len(d); k = sum(1 for x in d if x*direction > 0)
    if n == 0: return 1.0, 0, 0
    p = sum(comb(n, i) for i in range(k, n+1)) / 2**n
    return p, k, n

def fmt(x, nd=3): return f"{x:.{nd}f}"

PROMPTS = list(range(1, 11))
report = ["# Multi-prompt campaign — auto-generated stats",
          f"\n(generated by stats.py; npz cache in repro/0718/npz)\n"]

# ---------------- LC ----------------
def lc_video(arm, rep, p):
    g = glob.glob(f"results/multiprompt/lc/{arm}_rep{rep}/p{p}/*/segment_1.mp4")
    return g[0] if g else None

lc_rows, lc_diffs = [], {"f93_psnr": [], "f93_ssim": [], "f93_lpips": [], "vb": []}
for p in PROMPTS:
    ref = lc_video("bf16", 0, p)
    if not ref: lc_rows.append(f"| {p} | MISSING bf16 | | | |"); continue
    arms = {}
    for arm, reps in (("qvg", 3), ("pca", 1)):
        vals = []
        for r in range(reps):
            t = lc_video(arm, r, p)
            if not t: continue
            P, S, L = ref_metrics(ref, t, f"lc_p{p}_{arm}{r}")
            vals.append((P[93], S[93], L[93], P[93:].mean(), S[93:].mean(), L[93:].mean()))
        if vals: arms[arm] = np.array(vals).mean(axis=0)
    vb_p = vbench(lc_video("pca", 0, p))["full"] if lc_video("pca", 0, p) else np.nan
    vb_q = vbench(lc_video("qvg", 0, p))["full"] if lc_video("qvg", 0, p) else np.nan
    vb_b = vbench(ref)["full"]
    if "qvg" in arms and "pca" in arms:
        q, c = arms["qvg"], arms["pca"]
        lc_diffs["f93_psnr"].append(c[0]-q[0]); lc_diffs["f93_ssim"].append(c[1]-q[1])
        lc_diffs["f93_lpips"].append(c[2]-q[2]); lc_diffs["vb"].append(vb_p-vb_q)
        lc_rows.append(f"| {p} | {fmt(q[0],2)}/{fmt(q[1],4)}/{fmt(q[2],4)} | {fmt(c[0],2)}/{fmt(c[1],4)}/{fmt(c[2],4)} | {fmt(c[0]-q[0],2)} | {fmt(vb_b,1)}/{fmt(vb_q,1)}/{fmt(vb_p,1)} |")

report.append("## LC — f93 PSNR/SSIM/LPIPS (QVG=mean of 3 same-seed reps) + VBench(full)\n")
report.append("| p | QVG f93 | PCA f93 | ΔPSNR | VB b/q/p |")
report.append("|---|---|---|---|---|")
report += lc_rows
if lc_diffs["f93_psnr"]:
    d = np.array(lc_diffs["f93_psnr"]); pv, k, n = sign_test(d)
    report.append(f"\n**LC f93 ΔPSNR (pca−qvg): mean {fmt(d.mean(),3)} ± {fmt(d.std(),3)}, win {k}/{n}, sign-test p={fmt(pv,4)}**")
    for key, direction, label in (("f93_ssim",1,"ΔSSIM"),("f93_lpips",-1,"ΔLPIPS"),("vb",1,"ΔVBench")):
        d = np.array(lc_diffs[key]); pv, k, n = sign_test(d, direction)
        report.append(f"LC {label}: mean {fmt(d.mean(),4)}, win {k}/{n}, p={fmt(pv,4)}")

# ---------------- HY ----------------
report.append("\n## HY — mean over frames [13:] (post context-chunk), seeds paired\n")
report.append("| seed | QVG | PCA | ΔPSNR | VB b/q/p |")
report.append("|---|---|---|---|---|")
hy_d = {"psnr": [], "ssim": [], "lpips": [], "vb": []}
for s in range(5):
    ref = f"results/multiprompt/hy/bf16_s{s}/0-{s}.mp4"
    tq = f"results/multiprompt/hy/qvg_s{s}/0-{s}.mp4"
    tc = f"results/multiprompt/hy/pca_s{s}/0-{s}.mp4"
    if not all(os.path.exists(x) for x in (ref, tq, tc)):
        report.append(f"| {s} | MISSING | | | |"); continue
    Pq, Sq, Lq = ref_metrics(ref, tq, f"hy_s{s}_qvg")
    Pc, Sc, Lc = ref_metrics(ref, tc, f"hy_s{s}_pca")
    q = (Pq[13:].mean(), Sq[13:].mean(), Lq[13:].mean())
    c = (Pc[13:].mean(), Sc[13:].mean(), Lc[13:].mean())
    vb_b, vb_q, vb_p = vbench(ref)["full"], vbench(tq)["full"], vbench(tc)["full"]
    hy_d["psnr"].append(c[0]-q[0]); hy_d["ssim"].append(c[1]-q[1]); hy_d["lpips"].append(c[2]-q[2]); hy_d["vb"].append(vb_p-vb_q)
    report.append(f"| {s} | {fmt(q[0],2)}/{fmt(q[1],4)}/{fmt(q[2],4)} | {fmt(c[0],2)}/{fmt(c[1],4)}/{fmt(c[2],4)} | {fmt(c[0]-q[0],2)} | {fmt(vb_b,1)}/{fmt(vb_q,1)}/{fmt(vb_p,1)} |")
if hy_d["psnr"]:
    d = np.array(hy_d["psnr"]); pv, k, n = sign_test(d)
    report.append(f"\n**HY ΔPSNR (pca−qvg): mean {fmt(d.mean(),3)} ± sem {fmt(d.std()/max(1,np.sqrt(len(d))),3)}, win {k}/{n}, sign-test p={fmt(pv,4)}**")
    for key, direction, label in (("ssim",1,"ΔSSIM"),("lpips",-1,"ΔLPIPS"),("vb",1,"ΔVBench")):
        d = np.array(hy_d[key]); pv, k, n = sign_test(d, direction)
        report.append(f"HY {label}: mean {fmt(d.mean(),4)}, win {k}/{n}, p={fmt(pv,4)}")

# ---------------- SF ----------------
def sf_video(arm, rep, p, f=180):
    g = glob.glob(f"results/multiprompt/sf/{arm}_rep{rep}_f{f}/p{p}/*.mp4")
    return g[0] if g else None

report.append("\n## SF — VBench700 (180-latent videos; QVG=mean of 3 reps) + 1400f probe\n")
report.append("| p | BF16 | QVG700 | PCA700 | Δ700 | QVG1400 | PCA1400 |")
report.append("|---|---|---|---|---|---|---|")
sf_d, sf_d14 = [], []
for p in PROMPTS:
    vb, vq, vc = sf_video("bf16", 0, p), [sf_video("qvg", r, p) for r in range(3)], sf_video("pca", 0, p)
    b7 = vbench(vb)["700"] if vb else np.nan
    q7s = [vbench(v)["700"] for v in vq if v]
    q7 = np.mean(q7s) if q7s else np.nan
    c7 = vbench(vc)["700"] if vc else np.nan
    q14v, c14v = sf_video("qvg", 0, p, 360), sf_video("pca", 0, p, 360)
    q14 = vbench(q14v).get("1400", np.nan) if q14v else np.nan
    c14 = vbench(c14v).get("1400", np.nan) if c14v else np.nan
    if not (np.isnan(q7) or np.isnan(c7)): sf_d.append(c7-q7)
    if not (np.isnan(q14) or np.isnan(c14)): sf_d14.append(c14-q14)
    report.append(f"| {p} | {fmt(b7,2)} | {fmt(q7,2)} | {fmt(c7,2)} | {fmt(c7-q7,2)} | {fmt(q14,2)} | {fmt(c14,2)} |")
if sf_d:
    d = np.array(sf_d); pv, k, n = sign_test(d)
    report.append(f"\n**SF ΔVBench700 (pca−qvg): mean {fmt(d.mean(),3)} ± {fmt(d.std(),3)}, win {k}/{n}, sign-test p={fmt(pv,4)}**")
if sf_d14:
    d = np.array(sf_d14)
    report.append(f"SF ΔVBench1400: mean {fmt(d.mean(),3)}, win {sum(x>0 for x in d)}/{len(d)}")

out = "repro/0718/stats-output.md"
open(out, "w").write("\n".join(report) + "\n")
print("\n".join(report))
print(f"\nwritten to {out}")
